### ISSUE TITLE
pytorch版本的CLUE没有提供现成的模型权重文件吗

### ISSUE THREAD

**Issue by moluchase** [CLUEbenchmark/CLUE#58]
rt
是不是先得下载对应模型tf版本的权重文件
然后执行类似这样的脚本convert_albert_original_tf_checkpoint_to_pytorch.py将tf转为pytorch文件???

**Comment by moluchase** [comment]
在https://github.com/brightmart/albert_zh上面下载的`albert_base_zh(额外训练了1.5亿个实例即 36k steps * batch_size 4096)`模型使用脚本convert_albert_original_tf_checkpoint_to_pytorch.py转换出错。。。

**Comment by lonePatient** [comment]
@moluchase 你好，回头模型文件，专门收集下以及转化，放到共享盘，另外该albert转化报什么错误吗？

**Comment by moluchase** [comment]
> @moluchase 你好，回头模型文件，专门收集下以及转化，放到共享盘，另外该albert转化报什么错误吗？
INFO:transformers.modeling_albert:Converting TensorFlow checkpoint from .../workspace/CLUE_pytorch/prev_trained_model/model_param/albert_base
ERROR:tensorflow:Couldn't match files for checkpoint .../workspace/CLUE_pytorch/prev_trained_model/model_param/albert_base/.
ERROR:tensorflow:Couldn't match files for checkpoint .../workspace/CLUE_pytorch/prev_trained_model/model_param/albert_base/.
Traceback (most recent call last):
  File "convert_albert_original_tf_checkpoint_to_pytorch.py", line 51, in <module>
    args.pytorch_dump_path)
  File "convert_albert_original_tf_checkpoint_to_pytorch.py", line 22, in convert_tf_checkpoint_to_pytorch
    load_tf_weights_in_albert(model, config, tf_checkpoint_path)
  File ".../workspace/CLUE_pytorch/transformers/modeling_albert.py", line 61, in load_tf_weights_in_albert
    init_vars = tf.train.list_variables(tf_path)
  File ".../anaconda3/envs/cuda100/lib/python3.7/site-packages/tensorflow_core/python/training/checkpoint_utils.py", line 97, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File ".../anaconda3/envs/cuda100/lib/python3.7/site-packages/tensorflow_core/python/training/checkpoint_utils.py", line 65, in load_checkpoint
    "given directory %s" % ckpt_dir_or_file)
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory .../workspace/CLUE_pytorch/prev_trained_model/model_param/albert_base
但是我下载的albert_base有checkpoint文件，是这个文件albert_base_zh_additional_36k_steps.zip解压的，其他几个模型我都尝试过，没有出现转换出错的问题

**Comment by lonePatient** [comment]
@moluchase checkpoint文件内容问题，你修改为：
```text
model_checkpoint_path: "albert_model.ckpt"
all_model_checkpoint_paths: "albert_model.ckpt"
```
